-- ============================================================
-- Tansu & Arda — Wedding RSVP: Supabase setup
--
-- Run this once in your Supabase project's SQL editor
-- (Dashboard → SQL Editor → New query → paste → Run).
-- It is idempotent — safe to run again after edits.
--
-- Afterwards, two manual steps in the dashboard:
--   1. Authentication → Users → "Add user": create the admin
--      account (email + password) you will log into /admin with.
--      Use the same email as in admin_emails below.
--   2. Authentication → Sign In / Up → disable "Allow new users
--      to sign up" (defense in depth — policies already check
--      admin_emails, but there is no reason to allow signups).
-- ============================================================

-- ── Tables ──────────────────────────────────────────────────

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  token text not null unique,
  name text not null,
  max_guests integer,                    -- null = unlimited
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined')),
  party_size integer,
  note text,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

-- Who may use the admin dashboard (checked by RLS policies).
create table if not exists public.admin_emails (
  email text primary key
);

-- ⚠️ CHANGE THIS to the email of the admin user you create:
insert into public.admin_emails (email)
values ('arda.theodore@gmail.com')
on conflict do nothing;

-- Default event settings (edit later from the admin dashboard).
insert into public.settings (key, value) values
  ('eventDate',    '2026-06-28T14:30:00+03:00'),
  ('rsvpDeadline', '2026-06-14T23:59:00+03:00'),
  ('venueName',    'Germencik Belediyesi'),
  ('venueAddress', 'Germencik, Aydın'),
  ('mapsUrl',      'https://maps.google.com/?q=Germencik+Belediyesi,+Ayd%C4%B1n'),
  ('schedule',     '14:30 | Nikah Töreni | Ceremony'),
  ('storyUrl',     '/story/')
on conflict do nothing;

-- ── Row Level Security ───────────────────────────────────────

alter table public.invitations  enable row level security;
alter table public.settings     enable row level security;
alter table public.admin_emails enable row level security;

-- Admin check. SECURITY DEFINER so it can read admin_emails even though
-- that table has no policies of its own.
create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_emails
    where email = coalesce(auth.jwt() ->> 'email', '')
  );
$$;

-- Invitations: admins only. Guests never touch the table directly —
-- they go through the RPCs below, which look rows up by token.
drop policy if exists "admin full access" on public.invitations;
create policy "admin full access" on public.invitations
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Settings: anyone may read (date, venue, deadline are public to guests);
-- only admins may write.
drop policy if exists "settings are readable" on public.settings;
create policy "settings are readable" on public.settings
  for select to anon, authenticated
  using (true);

drop policy if exists "admin writes settings" on public.settings;
create policy "admin writes settings" on public.settings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- admin_emails: no policies — nobody reads or writes it through the API.
-- Manage it from the SQL editor only.

-- ── Guest-facing RPCs ────────────────────────────────────────
-- SECURITY DEFINER: they bypass RLS, but only ever touch the single row
-- matching the caller's unguessable token.

create or replace function public.get_invitation(p_token text)
returns table (
  name text,
  max_guests integer,
  status text,
  party_size integer,
  note text
)
language sql stable security definer
set search_path = public
as $$
  select i.name, i.max_guests, i.status, i.party_size, i.note
  from public.invitations i
  where i.token = p_token;
$$;

create or replace function public.submit_rsvp(
  p_token text,
  p_answer text,
  p_party_size integer,
  p_note text
)
returns table (status text, party_size integer)
language plpgsql security definer
set search_path = public
as $$
declare
  v_deadline timestamptz;
  v_max integer;
  v_size integer;
begin
  if p_answer not in ('accepted', 'declined') then
    raise exception 'invalid';
  end if;

  begin
    select s.value::timestamptz into v_deadline
    from public.settings s where s.key = 'rsvpDeadline';
  exception when others then
    v_deadline := null;  -- unparsable deadline: fail open, admin will notice
  end;
  if v_deadline is not null and now() > v_deadline then
    raise exception 'locked';
  end if;

  select i.max_guests into v_max
  from public.invitations i where i.token = p_token;
  if not found then
    raise exception 'invalid';
  end if;

  v_size := greatest(1, coalesce(p_party_size, 1));
  if v_max is not null then
    v_size := least(v_size, v_max);
  end if;
  v_size := least(v_size, 99);
  if p_answer = 'declined' then
    v_size := 0;
  end if;

  return query
  update public.invitations i
  set status       = p_answer,
      party_size   = v_size,
      note         = nullif(left(coalesce(p_note, ''), 2000), ''),
      responded_at = now(),
      updated_at   = now()
  where i.token = p_token
  returning i.status, i.party_size;
end;
$$;

-- Lock the functions down to exactly the roles that need them.
revoke all on function public.is_admin()                              from public;
revoke all on function public.get_invitation(text)                    from public;
revoke all on function public.submit_rsvp(text, text, integer, text)  from public;
grant execute on function public.is_admin()                             to anon, authenticated;
grant execute on function public.get_invitation(text)                   to anon, authenticated;
grant execute on function public.submit_rsvp(text, text, integer, text) to anon, authenticated;
