-- ============================================================
-- Tansu & Arda — Wedding RSVP: Supabase setup
--
-- Run this once in your Supabase project's SQL editor
-- (Dashboard → SQL Editor → New query → paste → Run).
-- It is idempotent — safe to run again after edits.
--
-- Afterwards, two manual steps in the dashboard:
--   1. Authentication → Users → "Add user": create the admin
--      account (email + password) you will log into /admin with.
--      Use the same email as in admin_emails below.
--   2. Authentication → Sign In / Up → disable "Allow new users
--      to sign up" (defense in depth — policies already check
--      admin_emails, but there is no reason to allow signups).
-- ============================================================

-- ── Tables ──────────────────────────────────────────────────

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  token text not null unique,
  name text not null,
  max_guests integer,                    -- null = unlimited
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined')),
  party_size integer,
  note text,
  personal_note text,                    -- optional message from the couple
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- For projects that ran an earlier version of this script:
alter table public.invitations add column if not exists personal_note text;

create table if not exists public.settings (
  key text primary key,
  value text not null
);

-- Who may use the admin dashboard (checked by RLS policies).
create table if not exists public.admin_emails (
  email text primary key
);

-- ⚠️ These emails may use the admin dashboard. Each also needs a user
-- account created under Authentication → Users with the same email.
insert into public.admin_emails (email)
values
  ('arda.theodore@gmail.com'),
  ('tansubicakcioglu@gmail.com')
on conflict do nothing;

-- Default event settings (edit later from the admin dashboard).
insert into public.settings (key, value) values
  ('eventDate',    '2026-06-28T14:30:00+03:00'),
  ('rsvpDeadline', '2026-06-14T23:59:00+03:00'),
  ('venueName',    'Germencik Belediyesi'),
  ('venueAddress', 'Germencik, Aydın'),
  ('mapsUrl',      'https://maps.google.com/?q=Germencik+Belediyesi,+Ayd%C4%B1n'),
  ('schedule',     '14:30 | Nikah Töreni | Ceremony'),
  ('storyUrl',     '/story/'),
  ('coupleNames',  'Tansu & Arda'),
  ('cardTilt',     '0'),
  ('dateStyle',    'date'),
  ('nightFrom',    '9'),
  ('ogTitle',      'Tansu & Arda — Düğün Davetiyesi'),
  ('ogDescription','Düğünümüze davetlisiniz · 28 Haziran 2026 · Germencik, Aydın')
on conflict do nothing;

-- Story-site strings that don't belong to a single chapter (nav labels,
-- hero kicker, closing lines). Edited from the dashboard's Story editor.
insert into public.settings (key, value) values
('storyTr', '{"navStory":"Hikâyemiz","navTimeline":"Zaman Tüneli","scroll":"kaydır","top":"başa dön","heroKicker":"bir aşk hikâyesi","heroTagline":"Ad astra per aspera — küçük, sıradan mucizelerle yazılmış bir hikâye.","navStart":"Başlangıç","navEnd":"Sonsuza","closeSub":"…devam edecek.","closeCredit":"Tansu & Arda — ve tabii ki Hecate ile Didi","closeBtn":"kedileri salıver"}'),
  ('storyEn', '{"navStory":"Our Story","navTimeline":"Timeline","scroll":"scroll","top":"back to the beginning","heroKicker":"the story of","heroTagline":"Ad astra per aspera — a story written in small, ordinary miracles.","navStart":"Start","navEnd":"Forever","closeSub":"…to be continued.","closeCredit":"Tansu & Arda — and Hecate & Didi, of course","closeBtn":"release the cats"}')
on conflict do nothing;


-- Story / timeline chapters. Each row is one chapter of the love story,
-- shown both as a scroll section and as a timeline slide. `photos` is a
-- JSON array of filenames living in public/story/assets/.
create table if not exists public.story_chapters (
  id bigint generated by default as identity primary key,
  position integer not null default 0,
  slug text not null unique,
  photos jsonb not null default '[]'::jsonb,
  photo_layout text not null default 'carousel'
    check (photo_layout in ('carousel', 'carousel-bare', 'stack', 'grid', 'single')),
  photo_fit text not null default 'cover'
    check (photo_fit in ('cover', 'contain')),
  tilt real not null default 0,
  visible boolean not null default true,
  night boolean not null default false,   -- shown in the dark, after-dusk part
  tr jsonb not null default '{}'::jsonb,
  en jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.story_chapters (position, slug, photos, photo_fit, tilt, night, tr, en) values
  (1, 'c1', '[]'::jsonb, 'cover', -2, false, '{"nav":"Tanışma","kicker":"Birinci Bölüm","date":"Sonbahar 2019","title":"İlk Karşılaşma","cap":"her şeyin başladığı yer","body":"Kalabalık bir oda, ortak bir şaka ve söylediklerini birden unutan iki kişi. İlk kim konuştu, ikimiz de hatırlamıyoruz — yalnızca akşamın fazlasıyla kısa geldiğini. Bazı hikâyeler havai fişeklerle başlamaz; bizimki kalıcı bir gülümsemeyle başladı.","tl":"Kalabalık bir oda, ortak bir şaka ve fazlasıyla kısa gelen bir akşam."}'::jsonb, '{"nav":"Meet","kicker":"Chapter One","date":"Autumn 2019","title":"First Meet","cap":"where it all began","body":"A crowded room, a shared joke, and two people who suddenly forgot what they had been saying. Neither of us remembers who spoke first — only that the evening felt far too short. Some stories don’t begin with fireworks; ours began with a smile that stayed.","tl":"A crowded room, a shared joke, and an evening that felt far too short."}'::jsonb),
  (2, 'c2', '[]'::jsonb, 'cover', 2, false, '{"nav":"Buluşma","kicker":"İkinci Bölüm","date":"Birkaç hafta sonra","title":"İlk Buluşma","cap":"en uzun kısa akşam","body":"Bir kahve yemeğe, yemek de hiçbirimizin bitmesini istemediği yavaş bir yürüyüşe dönüştü. Kafe etrafımızda kapandı, fark etmedik bile. Kimin daha heyecanlı olduğunu hâlâ tatlı tatlı tartışıyoruz.","tl":"Bir kahve yemeğe, yemek de bitmesin istediğimiz bir yürüyüşe dönüştü."}'::jsonb, '{"nav":"Date","kicker":"Chapter Two","date":"A few weeks later","title":"First Date","cap":"the longest short evening","body":"One coffee became dinner, and dinner became a slow walk that neither of us wanted to end. The café closed around us and we barely noticed. We still argue, gently, about who was more nervous.","tl":"One coffee became dinner, and dinner became a walk neither of us wanted to end."}'::jsonb),
  (3, 'c3', '[]'::jsonb, 'cover', -1.5, false, '{"nav":"Öpücük","kicker":"Üçüncü Bölüm","date":"Kısa bir süre sonra","title":"İlk Öpücük","cap":"nazik bir sokak lambasının altında","body":"Acele etmeyen bir iyi geceler. Sokak sessizdi, hava serindi ve uzun bir saniye boyunca bütün şehir kibarca başka tarafa baktı. Ondan sonra geri dönüş yoktu — istemedik de.","tl":"Acele etmeyen bir iyi geceler, nazik bir sokak lambasının altında."}'::jsonb, '{"nav":"Kiss","kicker":"Chapter Three","date":"Not long after","title":"First Kiss","cap":"under a kind streetlight","body":"A goodnight that took its time. The street was quiet, the air was cool, and for one long second the whole city seemed to look away politely. After that, there was no going back — and we never wanted to.","tl":"A goodnight that took its time, under a kind streetlight."}'::jsonb),
  (4, 'c4', '["hecate.jpeg"]'::jsonb, 'cover', 1.8, false, '{"nav":"Hecate","kicker":"Dördüncü Bölüm","date":"Bizi seçtiği gün","title":"Hecate Geliyor","cap":"Hecate, evin bekçisi","body":"Altın gözlü, küçük kırmızı çıngıraklı kara bir gölge. Kara kedilerin insanlarını seçtiğini söylerler — Hecate içeri yürüdü, bizi iyice teftiş etti ve idare edeceğimize karar verdi. İki, üç oldu.","tl":"Altın gözlü kara bir gölge içeri girdi, bizi teftiş etti ve kalmaya karar verdi."}'::jsonb, '{"nav":"Hecate","kicker":"Chapter Four","date":"The day she chose us","title":"Enter Hecate","cap":"Hecate, keeper of the house","body":"A black shadow with golden eyes and a small red bell. They say black cats choose their people — Hecate simply walked in, inspected us thoroughly, and decided we would do. Two became three.","tl":"A black shadow with golden eyes walked in, inspected us, and decided to stay."}'::jsonb),
  (5, 'c5', '[]'::jsonb, 'cover', -2.2, false, '{"nav":"Yazlar","kicker":"Beşinci Bölüm","date":"Aradaki yıllar","title":"Ege Yazları","cap":"tuz, çam ve yavaş akşamlar","body":"Kötü çalma listeleri ve iyi arkadaşlıkla yol maceraları. Akşam yemeğinde omuzlarımızda hâlâ kuruyan deniz suyu. O küçük yolculukların arasında bir yerde ev, bir mekân olmaktan çıkıp birbirimiz oldu.","tl":"Yol maceralarının arasında bir yerde ev, birbirimiz oldu."}'::jsonb, '{"nav":"Trips","kicker":"Chapter Five","date":"The years in between","title":"Aegean Summers","cap":"salt, pine, and slow evenings","body":"Road trips with bad playlists and good company. Sea water still drying on our shoulders at dinner. Somewhere between all those small journeys, home stopped being a place and started being each other.","tl":"Somewhere between the road trips, home stopped being a place and became each other."}'::jsonb),
  (6, 'c6', '["didi.jpeg"]'::jsonb, 'cover', 2.2, false, '{"nav":"Didi","kicker":"Altıncı Bölüm","date":"Küçük, gürültülü bir mucize","title":"Didi Geliyor","cap":"Didi, küçük ama yetkili","body":"Avuç içi kadar, biberonla beslenen ve evi kendisinin yönettiğine emin. Didi bir çay fincanından hafif geldi ve evdeki gürültüyü anında ikiye katladı. Hecate tam bir hafta boyunca onaylamıyormuş gibi yaptı.","tl":"Avuç içi kadar, biberonla beslenen ve evi yönettiğine emin."}'::jsonb, '{"nav":"Didi","kicker":"Chapter Six","date":"A tiny, loud miracle","title":"Enter Didi","cap":"Didi, small but in charge","body":"Palm-sized, bottle-fed, and utterly convinced she runs the place. Didi arrived weighing less than a teacup and immediately doubled the noise in the house. Hecate pretended to disapprove for exactly one week.","tl":"Palm-sized, bottle-fed, and utterly convinced she runs the place."}'::jsonb),
  (7, 'c7', '[]'::jsonb, 'cover', -1.6, false, '{"nav":"Teklif","kicker":"Yedinci Bölüm","date":"Tek diz, tek soru","title":"Evlilik Teklifi","cap":"evet dedi","body":"Yüzük haftalarca saklandı; hazırlanan konuşma ise anında buharlaştı. Sonunda dört titrek kelime ve son derece emin bir cevap kaldı. Zorluklardan yıldızlara.","tl":"Dört titrek kelime ve emin bir cevap. Zorluklardan yıldızlara."}'::jsonb, '{"nav":"Proposal","kicker":"Chapter Seven","date":"One knee, one question","title":"The Proposal","cap":"she said yes","body":"The ring had been hiding for weeks; the speech evaporated on arrival. In the end it was four shaky words and one certain answer. Zorluklardan yıldızlara — through hardships, to the stars.","tl":"Four shaky words and one certain answer. Zorluklardan yıldızlara."}'::jsonb),
  (8, 'c8', '[]'::jsonb, 'cover', 1.4, false, '{"nav":"Yeni","kicker":"Sekizinci Bölüm","date":"Cesur bir karar","title":"Yeni Bir Sayfa","cap":"birlikte kuruyoruz","body":"Tansu bir kapıyı kapatıp bizimkini araladı: kendi işimizi birlikte kurmak için işinden ayrıldı. Bir sıçrayıştı — ve bu hikâyedeki her güzel sıçrayış gibi, el ele atladık.","tl":"Tansu bir kapıyı kapatıp bizimkini araladı — el ele atladık."}'::jsonb, '{"nav":"Anew","kicker":"Chapter Eight","date":"A brave decision","title":"A New Chapter","cap":"building it together","body":"Tansu closed one door to open ours: she left her job to build something of our own, together. It was a leap — and like every good leap in this story, we took it holding hands.","tl":"Tansu closed one door to open ours — a leap we took holding hands."}'::jsonb),
  (9, 'c9', '["invitation.png"]'::jsonb, 'contain', -1.4, true, '{"nav":"Davetiye","kicker":"Dokuzuncu Bölüm","date":"Ad astra per aspera","title":"Davetiye","cap":"","body":"Hikâyemizi yıldızlara çizdik — tarot kartları, roketler, bir kara kedi ve bir küçük kedi — ve dünyaya gönderdik. Hecate ve Didi de tabii ki posterde: aileyi zaten onlar yönetiyor.","tl":"Yıldızlara çizilmiş hikâyemiz — posterde Hecate ve Didi ile."}'::jsonb, '{"nav":"Invite","kicker":"Chapter Nine","date":"Ad astra per aspera","title":"The Invitation","cap":"","body":"We drew our story in the stars — tarot cards, rockets, one black cat and one small one — and sent it out into the world. Hecate and Didi made the poster, of course. They practically run the family.","tl":"Our story drawn in the stars — with Hecate and Didi on the poster, naturally."}'::jsonb),
  (10, 'c10', '[]'::jsonb, 'cover', 1.8, true, '{"nav":"Düğün","kicker":"Onuncu Bölüm","date":"28 Haziran 2026","title":"Düğünümüz","cap":"en kolay evet","body":"Sıcak bir haziran öğleden sonrasında, sevdiğimiz herkesin arasında hayatımızın en kolay evet’ini söyledik. Yedi yılın küçük, sıradan mucizeleri; saat iki buçukta imzalandı ve mühürlendi.","tl":"Germencik Belediyesi, Aydın — hayatımızın en kolay evet’i."}'::jsonb, '{"nav":"Wedding","kicker":"Chapter Ten","date":"28 June 2026","title":"Our Wedding","cap":"the easiest yes","body":"On a warm June afternoon, surrounded by everyone we love, we said the easiest yes of our lives. Seven years of small ordinary miracles, signed and sealed at half past two.","tl":"Germencik Belediyesi, Aydın — the easiest yes of our lives."}'::jsonb)
on conflict (slug) do nothing;

-- Widen the photo layout check for projects created before 'single' existed.
alter table public.story_chapters drop constraint if exists story_chapters_photo_layout_check;
alter table public.story_chapters add constraint story_chapters_photo_layout_check
  check (photo_layout in ('carousel', 'carousel-bare', 'stack', 'grid', 'single'));


-- Five extra chapters (hidden). Toggle them on and fill them in from the
-- dashboard when you want more than ten. Kept empty so they never show
-- until enabled.
insert into public.story_chapters (position, slug, photos, photo_fit, tilt, night, visible, tr, en) values
  (11, 'c11', '[]'::jsonb, 'cover',  1.6, true, false, '{}'::jsonb, '{}'::jsonb),
  (12, 'c12', '[]'::jsonb, 'cover', -1.8, true, false, '{}'::jsonb, '{}'::jsonb),
  (13, 'c13', '[]'::jsonb, 'cover',  2.0, true, false, '{}'::jsonb, '{}'::jsonb),
  (14, 'c14', '[]'::jsonb, 'cover', -1.5, true, false, '{}'::jsonb, '{}'::jsonb),
  (15, 'c15', '[]'::jsonb, 'cover',  1.4, true, false, '{}'::jsonb, '{}'::jsonb)
on conflict (slug) do nothing;

-- Counters for the general (universal) invitation link.
create table if not exists public.general_stats (
  kind text primary key,
  count bigint not null default 0
);
insert into public.general_stats (kind, count) values ('opens', 0), ('yes', 0)
on conflict do nothing;

-- ── Row Level Security ───────────────────────────────────────

alter table public.invitations    enable row level security;
alter table public.story_chapters enable row level security;
alter table public.general_stats  enable row level security;
alter table public.settings     enable row level security;
alter table public.admin_emails enable row level security;

-- Admin check. SECURITY DEFINER so it can read admin_emails even though
-- that table has no policies of its own.
create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_emails
    where email = coalesce(auth.jwt() ->> 'email', '')
  );
$$;

-- Invitations: admins only. Guests never touch the table directly —
-- they go through the RPCs below, which look rows up by token.
drop policy if exists "admin full access" on public.invitations;
create policy "admin full access" on public.invitations
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Settings: anyone may read (date, venue, deadline are public to guests);
-- only admins may write.
drop policy if exists "settings are readable" on public.settings;
create policy "settings are readable" on public.settings
  for select to anon, authenticated
  using (true);

drop policy if exists "admin writes settings" on public.settings;
create policy "admin writes settings" on public.settings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Story chapters: readable by everyone (the story site is public),
-- writable only by admins.
drop policy if exists "story is readable" on public.story_chapters;
create policy "story is readable" on public.story_chapters
  for select to anon, authenticated
  using (true);

drop policy if exists "admin writes story" on public.story_chapters;
create policy "admin writes story" on public.story_chapters
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- General stats: readable by everyone (the counts aren't secret), and only
-- ever changed through the SECURITY DEFINER RPC below.
drop policy if exists "general stats readable" on public.general_stats;
create policy "general stats readable" on public.general_stats
  for select to anon, authenticated
  using (true);

-- admin_emails: no policies — nobody reads or writes it through the API.
-- Manage it from the SQL editor only.

-- ── Guest-facing RPCs ────────────────────────────────────────
-- SECURITY DEFINER: they bypass RLS, but only ever touch the single row
-- matching the caller's unguessable token.

-- (dropped first because the return type changed between versions —
-- CREATE OR REPLACE cannot alter a function's return type)
drop function if exists public.get_invitation(text);
create function public.get_invitation(p_token text)
returns table (
  name text,
  max_guests integer,
  status text,
  party_size integer,
  note text,
  personal_note text
)
language sql stable security definer
set search_path = public
as $$
  select i.name, i.max_guests, i.status, i.party_size, i.note, i.personal_note
  from public.invitations i
  where i.token = p_token;
$$;

create or replace function public.submit_rsvp(
  p_token text,
  p_answer text,
  p_party_size integer,
  p_note text
)
returns table (status text, party_size integer)
language plpgsql security definer
set search_path = public
as $$
declare
  v_deadline timestamptz;
  v_max integer;
  v_size integer;
begin
  if p_answer not in ('accepted', 'declined') then
    raise exception 'invalid';
  end if;

  begin
    select s.value::timestamptz into v_deadline
    from public.settings s where s.key = 'rsvpDeadline';
  exception when others then
    v_deadline := null;  -- unparsable deadline: fail open, admin will notice
  end;
  if v_deadline is not null and now() > v_deadline then
    raise exception 'locked';
  end if;

  select i.max_guests into v_max
  from public.invitations i where i.token = p_token;
  if not found then
    raise exception 'invalid';
  end if;

  v_size := greatest(1, coalesce(p_party_size, 1));
  if v_max is not null then
    v_size := least(v_size, v_max);
  end if;
  v_size := least(v_size, 99);
  if p_answer = 'declined' then
    v_size := 0;
  end if;

  return query
  update public.invitations i
  set status       = p_answer,
      party_size   = v_size,
      note         = nullif(left(coalesce(p_note, ''), 2000), ''),
      responded_at = now(),
      updated_at   = now()
  where i.token = p_token
  returning i.status, i.party_size;
end;
$$;

-- Lock the functions down to exactly the roles that need them.
create or replace function public.general_track(p_kind text)
returns void
language plpgsql security definer
set search_path = public
as $$
begin
  if p_kind not in ('opens', 'yes') then
    return;
  end if;
  update public.general_stats set count = count + 1 where kind = p_kind;
end;
$$;

revoke all on function public.is_admin()                              from public;
revoke all on function public.general_track(text)                    from public;
revoke all on function public.get_invitation(text)                    from public;
revoke all on function public.submit_rsvp(text, text, integer, text)  from public;
grant execute on function public.is_admin()                             to anon, authenticated;
grant execute on function public.get_invitation(text)                   to anon, authenticated;
grant execute on function public.submit_rsvp(text, text, integer, text) to anon, authenticated;
grant execute on function public.general_track(text)                    to anon, authenticated;
